Assignment 1 : Numpy

In [3]:
# 1)Import NumPy and print its version.
import numpy as np

print(np.__version__)

2.1.3


In [4]:
# 2)Make an array from the hours logged column

import pandas as pd
import numpy as np

df = pd.read_csv("it_services_tickets_cleaned.csv")

hours = np.array(df["hours_logged"])

print(hours)

[  nan  1.34  7.   ... 47.    2.     nan]


/tmp/ipykernel_725/274030634.py:6: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("it_services_tickets_cleaned.csv")


In [5]:
# 3)Print the shape, the size and the data type of that array.
print("Shape:", hours.shape)
print("Size:", hours.size)
print("Data type:", hours.dtype)

Shape: (48123,)
Size: 48123
Data type: float64


In [6]:
# 4)Make an array of the numbers 1 to 50 using arange.
arr = np.arange(1, 51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [7]:
# 5)Make 10 evenly spaced numbers between 0 and 100 using linspace.
arr = np.linspace(0, 100, 10)
print(arr)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [8]:
# 6)Make an array of 10 zeros and an array of 10 ones.
zeros = np.zeros(10)
ones = np.ones(10)

print("Zeros:", zeros)
print("Ones:", ones)

Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
# 7)Make a 3 by 3 array of random numbers using seed 42.
np.random.seed(42)
random_array = np.random.rand(3, 3)
print(random_array)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [10]:
# 8)Make a 2-D array from the hours logged and billing rate columns.
two_d_array = df[["hours_logged", "billing_rate_(usd)"]].to_numpy()
print(two_d_array)

[[   nan  39.45]
 [  1.34  33.15]
 [  7.    48.1 ]
 ...
 [ 47.      nan]
 [  2.   116.76]
 [   nan  89.02]]


In [11]:
# 9)Print how many dimensions that 2-D array has
print("Dimensions:", two_d_array.ndim)

Dimensions: 2


In [12]:
# 10)Print the first 5 values of the hours array.
print("First 5:", hours[:5])

First 5: [  nan  1.34  7.   34.63 12.76]


In [13]:
# 11)Print the last 5 values of the hours array.
print("Last 5:", hours[-5:])

Last 5: [50.  4. 47.  2. nan]


In [14]:
# 12)Print every second value from the first 20 values.
print("Every second value:", hours[:20:2])

Every second value: [   nan   7.    12.76    nan   1.66    nan  11.63  28.     0.59 253.85]


In [15]:
# 13)Reverse the array.
print("Reversed:", hours[::-1])

Reversed: [  nan  2.   47.   ...  7.    1.34   nan]


In [16]:
# 14)Find the sum of the hours array.
print("Sum:", np.nansum(hours))

Sum: 2290016.55


In [17]:
# 15)Find the mean, the minimum and the maximum of the hours array.
print("Mean:", np.nanmean(hours))
print("Minimum:", np.nanmin(hours))
print("Maximum:", np.nanmax(hours))

Mean: 63.16764267784735
Minimum: -12.5
Maximum: 9888.01


In [18]:
# 16)Find the standard deviation.
print("Standard deviation:", np.nanstd(hours))


Standard deviation: 493.3142529221527


In [19]:
# 17)Find the median.
print("Median:", np.nanmedian(hours))

Median: 13.1


In [20]:
# 18)Count how many values are missing in the array.
print("Missing values:", np.isnan(hours).sum())

Missing values: 11870


In [21]:
# 19)Find the mean while ignoring the missing values
print("Mean ignoring NaN:", np.nanmean(hours))

Mean ignoring NaN: 63.16764267784735


In [22]:
# 20)Replace all the missing values with 0.
hours = np.nan_to_num(hours, nan=0)

print("Array after replacing NaN with 0:")
print(hours)

Array after replacing NaN with 0:
[ 0.    1.34  7.   ... 47.    2.    0.  ]


In [23]:
# 21)Count how many values are greater than 100.
print(np.sum(hours > 100))

1588


In [24]:
# 22)Show only the values that are greater than 100.
print(hours[hours > 100])

[ 253.85  128.   1900.66 ...  562.22  141.9   137.56]


In [25]:
# 23)Show the values that are between 10 and 50.
print(hours[(hours >= 10) & (hours <= 50)])

[34.63 12.76 15.3  ... 25.23 50.   47.  ]


In [26]:
# 24)Count how many values are negative.
print(np.sum(hours < 0))

136


In [27]:
# 25)Replace all the negative values with 0.
hours[hours < 0] = 0

In [28]:
# 26)Sort the array from smallest to largest.
sorted_hours = np.sort(hours)
print(sorted_hours)

[   0.      0.      0.   ... 8760.   9888.01 9888.01]


In [29]:
# 27)Find the position of the largest value.
print(np.argmax(hours))

10041


In [30]:
# 28)Find the position of the smallest value.
print(np.argmin(hours))



0


In [31]:
# 29)Find the 5 largest values.
print(np.sort(hours)[-5:])

[8760.   8760.   8760.   9888.01 9888.01]


In [32]:
# 30)Round every value to 1 decimal place.
hours = np.round(hours, 1)
print(hours)

[ 0.   1.3  7.  ... 47.   2.   0. ]


In [33]:
# 31)Multiply every value by 2.
hours_x2 = hours * 2
print(hours_x2)

[ 0.   2.6 14.  ... 94.   4.   0. ]


In [34]:
# 32)Add 10 to every value.

hours_plus_10 = hours + 10
print(hours_plus_10)

















[10.  11.3 17.  ... 57.  12.  10. ]


In [35]:
# 33)ltiply the hours array by the billing rate array.
hours = np.array(df["hours_logged"])

billing_rate = np.array(df["billing_rate_(usd)"])

total = hours * billing_rate
print(total)

[    nan  44.421 336.7   ...     nan 233.52      nan]


In [36]:
# 34)Check whether the two arrays have the same length.
print(len(hours) == len(billing_rate))

True


In [37]:
# 35)Use np.where to mark values above 24 as slow and the rest as fast.
speed = np.where(hours > 24, "slow", "fast")
print(speed)

['fast' 'fast' 'fast' ... 'slow' 'fast' 'fast']


In [38]:
# 36)Make an array of the unique priority values.
priority = np.array(df["priority"].dropna())

unique_priority = np.unique(priority)

print(unique_priority)

# priority = np.array(df["priority"])

# unique_priority = np.unique(priority)

# print(unique_priority)

[' ' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High' 'LOW'
 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4' 'PRIORITY'
 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3' 'p4']


In [39]:
# 37)Count how many times each unique priority value appears.
values, counts = np.unique(priority, return_counts=True)

print(values)
print(counts)

[' ' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High' 'LOW'
 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4' 'PRIORITY'
 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3' 'p4']
[  95  107 1931 1966 1934 1919   85 1993 2000 1950 2003 1945 1840 1949
 1941 1891 1969 1907 1950 1880    1 1971 1950 2023  125  130 1934 1898
 1988 1909]


In [40]:
# 38)Take the first 100 values and reshape them into a 10 by 10 array.
array_100 = hours[:100].reshape(10, 10)

print(array_100)

[[         nan  1.34000e+00  7.00000e+00  3.46300e+01  1.27600e+01
   1.53000e+01          nan  9.00000e+00  1.66000e+00          nan]
 [         nan  1.44000e+00  1.16300e+01  7.23100e+01  2.80000e+01
   1.01600e+01  5.90000e-01  7.00000e+00  2.53850e+02  4.20000e+00]
 [ 5.08100e+01  8.01000e+00  6.79400e+01          nan  3.27100e+01
           nan  6.91000e+00  3.08400e+01  3.51000e+00  4.34000e+00]
 [ 1.80000e+01  3.14400e+01  3.42000e+00  2.44600e+01          nan
   1.30000e+01  3.00200e+01  1.15100e+01  6.30200e+01  1.03000e+00]
 [         nan  3.92000e+00  2.02200e+01  2.41500e+01  8.40000e+01
           nan  2.70000e+01          nan  4.00000e+00  2.76000e+00]
 [ 1.12600e+01  2.40000e+01  5.26000e+00  1.40000e+01  5.00000e+00
   1.14100e+01          nan  1.80000e+01  1.28000e+02  1.54000e+01]
 [ 1.90066e+03  4.00000e+00  3.00000e+00  9.00000e+00  1.33350e+02
           nan  4.00000e+00          nan  2.00000e+00          nan]
 [ 2.05100e+01  1.13300e+01  5.99100e+01  1.00000e+00  

In [41]:
# 39)Transpose that 10 by 10 array.
transposed = array_100.T

print(transposed)

[[         nan          nan  5.08100e+01  1.80000e+01          nan
   1.12600e+01  1.90066e+03  2.05100e+01  1.91700e+01  1.30000e+01]
 [ 1.34000e+00  1.44000e+00  8.01000e+00  3.14400e+01  3.92000e+00
   2.40000e+01  4.00000e+00  1.13300e+01  1.78600e+01  1.09100e+01]
 [ 7.00000e+00  1.16300e+01  6.79400e+01  3.42000e+00  2.02200e+01
   5.26000e+00  3.00000e+00  5.99100e+01  9.21000e+00  8.00000e+00]
 [ 3.46300e+01  7.23100e+01          nan  2.44600e+01  2.41500e+01
   1.40000e+01  9.00000e+00  1.00000e+00  5.40000e+01  3.81000e+00]
 [ 1.27600e+01  2.80000e+01  3.27100e+01          nan  8.40000e+01
   5.00000e+00  1.33350e+02  2.29700e+01          nan  3.73680e+02]
 [ 1.53000e+01  1.01600e+01          nan  1.30000e+01          nan
   1.14100e+01          nan -1.20000e+01  2.00000e+01  1.13800e+01]
 [         nan  5.90000e-01  6.91000e+00  3.00200e+01  2.70000e+01
           nan  4.00000e+00          nan  6.00000e+00  3.36700e+01]
 [ 9.00000e+00  7.00000e+00  3.08400e+01  1.15100e+01  

In [42]:
# 40)atten it back into a 1-D array.
flattened = transposed.flatten()

print(flattened)

[         nan          nan  5.08100e+01  1.80000e+01          nan
  1.12600e+01  1.90066e+03  2.05100e+01  1.91700e+01  1.30000e+01
  1.34000e+00  1.44000e+00  8.01000e+00  3.14400e+01  3.92000e+00
  2.40000e+01  4.00000e+00  1.13300e+01  1.78600e+01  1.09100e+01
  7.00000e+00  1.16300e+01  6.79400e+01  3.42000e+00  2.02200e+01
  5.26000e+00  3.00000e+00  5.99100e+01  9.21000e+00  8.00000e+00
  3.46300e+01  7.23100e+01          nan  2.44600e+01  2.41500e+01
  1.40000e+01  9.00000e+00  1.00000e+00  5.40000e+01  3.81000e+00
  1.27600e+01  2.80000e+01  3.27100e+01          nan  8.40000e+01
  5.00000e+00  1.33350e+02  2.29700e+01          nan  3.73680e+02
  1.53000e+01  1.01600e+01          nan  1.30000e+01          nan
  1.14100e+01          nan -1.20000e+01  2.00000e+01  1.13800e+01
          nan  5.90000e-01  6.91000e+00  3.00200e+01  2.70000e+01
          nan  4.00000e+00          nan  6.00000e+00  3.36700e+01
  9.00000e+00  7.00000e+00  3.08400e+01  1.15100e+01          nan
  1.80000e

In [43]:
# 41)Join two arrays together using np.concatenate.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

joined = np.concatenate((arr1, arr2))

print(joined)

[1 2 3 4 5 6]


In [44]:
# 42)lit an array into 5 equal parts.
parts = np.array_split(hours, 5)

for part in parts:
    print(part)

[ nan 1.34 7.   ... 1.31  nan  nan]
[29.   47.42   nan ... 24.8  16.    7.18]
[14.76  2.61 39.   ...  4.94   nan 38.24]
[74.75 13.84   nan ...  7.26 23.27 32.  ]
[32.   11.99  5.43 ... 47.    2.     nan]


In [45]:
# 43)Find the 25th, 50th and 75th percentile.
print(np.percentile(hours, [25, 50, 75]))

[nan nan nan]


In [46]:
# 44)Find the cumulative sum of the first 20 values.
print(np.cumsum(hours[:20]))

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan]


In [47]:
# 45)Find the difference between each value and the one before it using np.diff
print(np.diff(hours))

[   nan   5.66  27.63 ...  43.   -45.      nan]


In [48]:
# 46)Keep every value inside the range 0 to 100 using np.clip.
clipped = np.clip(hours, 0, 100)

print(clipped)

[  nan  1.34  7.   ... 47.    2.     nan]


In [49]:
# 47)Convert the array to whole numbers.
whole_numbers = hours.astype(int)

print(whole_numbers)

[-9223372036854775808                    1                    7 ...
                   47                    2 -9223372036854775808]


/tmp/ipykernel_725/1364617618.py:2: RuntimeWarning: invalid value encountered in cast
  whole_numbers = hours.astype(int)


In [50]:
# 48)Copy the array, change one value in the copy, and show that the original did not change.
copy_hours = hours.copy()

copy_hours[0] = 999

print("Original:", hours[0])
print("Copy:", copy_hours[0])

Original: nan
Copy: 999.0


In [51]:
# 49)Save the array to a .npy file and load it back.
np.save("hours.npy", hours)

In [52]:
# 50)Find the total revenue using np.dot on the hours array and the rate array.
total_revenue = np.dot(hours, billing_rate)

print("Total revenue:", total_revenue)

Total revenue: nan
